puts('Hello '+'world')
puts('Hello '*3)
puts('Hello'[0])
puts('Hello'[1])
puts('Hello'[2])

puts('hello world'.capitalize())
puts('hello world'.upcase())
puts('hello world'.length())
puts('Hello world'.sub('world', 'programming'))
